stages:
    - build

image: docker:latest

# Can use UI to hide passwords
variables:
    IMAGE_NAME: hotrod-customer
    DOCKER_DRIVER: overlay2


services:
    - docker:dind

build:
    stage: build
    script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    # Build hotrod image
    - docker pull $CI_REGISTRY_USER/$IMAGE_NAME:latest
    - docker build \
      -t $CI_REGISTRY_USER/$IMAGE_NAME:$CI_COMMIT_SHA \
      --cache-from $CI_REGISTRY_USER/$IMAGE_NAME:latest \
      --build-arg git_pass=$GITLAB_TOKEN \
      --build-arg build_time=$(date +%s) .
    - docker push $CI_REGISTRY_USER/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_USER/$IMAGE_NAME:$CI_COMMIT_SHA  $CI_REGISTRY_USER/$IMAGE_NAME:latest
    - docker push $CI_REGISTRY_USER/$IMAGE_NAME:latest

